# Generated by Django 3.1 on 2020-08-21 15:45

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=16)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('address', models.TextField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('order_state', models.CharField(choices=[('submitted', 'submitted'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], max_length=20)),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza_order.pizza')),
            ],
        ),
    ]
