# Generated by Django 3.1 on 2020-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
